import os
import json
import math
import csv

def calculate_pass_at_k(n, c, k):
    """
    Calculates the probability of at least one success (entailment) in k draws
    from a pool of n generations containing c successes.
    """
    if k > n:
        return 0.0

    total_combinations = math.comb(n, k)

    if n - c < k:
        fail_combinations = 0
    else:
        fail_combinations = math.comb(n - c, k)
        
    return 1.0 - (fail_combinations / total_combinations)

def process_single_seed_file(input_filename):
    """
    Processes a single generations_n200.json file and returns a dictionary 
    of average Pass@K scores for that seed.
    """
    k_values = [1, 2, 4, 8, 16, 32, 64, 128]
    total_entries = 400
    
    sum_pass_at_k = {k: 0.0 for k in k_values}
    
    try:
        with open(input_filename, 'r', encoding='utf-8') as f:
            for i, line in enumerate(f):
                if i >= total_entries:
                    break
                
                data = json.loads(line)
                
                if 'responses' not in data:
                    continue
                
                responses = data['responses']
                n = len(responses)
                
                # Count successes (Entailment Score == 1)
                c = sum(1 for response in responses if response.get('ES') == 1)

                for k in k_values:
                    pass_at_k_score = calculate_pass_at_k(n, c, k)
                    sum_pass_at_k[k] += pass_at_k_score
                    
        # Calculate averages for this specific seed
        average_pass_at_k = {k: score / total_entries for k, score in sum_pass_at_k.items()}
        return average_pass_at_k
        
    except Exception as e:
        print(f"Error reading {input_filename}: {e}")
        return None

if __name__ == "__main__":
    
    # 1. Define configuration
    total_seeds = 25
    k_columns = [1, 2, 4, 8, 16, 32, 64, 128]
    output_csv_file = "all_seeds_pass_at_k.csv"
    
    # List to store results for the CSV
    all_results = []
    
    print(f"Aggregating Pass@K results for {total_seeds} seeds...")
    
    # 2. Iterate through all 25 seed folders
    for seed in range(2, total_seeds + 1):
        # Build the exact path based on your specified structure
        # Note: ensure "npo_" matches the exact casing generated by your previous script
        file_path = f"saves/eval/grad_{seed}/forget/temperature=1.0top_p=1.0/generations_n200_evaluated.json"
        
        if not os.path.exists(file_path):
            print(f"⚠️ Warning: File not found for seed {seed}: {file_path}")
            # Add a row of Nones/Errors if the file is missing
            missing_row = {'Seed': seed}
            missing_row.update({k: "Missing Data" for k in k_columns})
            all_results.append(missing_row)
            continue
            
        # Process the file
        seed_scores = process_single_seed_file(file_path)
        
        if seed_scores:
            # Prepare the row dictionary for the CSV Writer
            row_data = {'Seed': seed}
            row_data.update(seed_scores)
            all_results.append(row_data)
            print(f"✅ Processed Seed {seed}")
        else:
            print(f"❌ Failed to process Seed {seed}")

    # 3. Write results to CSV
    print(f"\nWriting results to {output_csv_file}...")
    
    # Define CSV headers
    fieldnames = ['Seed'] + k_columns
    
    with open(output_csv_file, mode='w', newline='', encoding='utf-8') as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
        
        writer.writeheader()
        for result in all_results:
            writer.writerow(result)
            
    print("Done! 🎉")